services:
  hexo-bridge:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
      - ./public:/public
  nginx:
    image: "nginx:alpine-slim"
    ports:
      - "8025:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    depends_on: 
      - hexo-bridge
